# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sb7OcJnQ5VbUNPwK37sv5DjEk0f4Bp5C
"""

!pip install pyspark

from pyspark import SparkContext, SparkConf

conf = SparkConf().setAppName("Surname Length").setMaster("local")
sc = SparkContext.getOrCreate(conf=conf)

surnames_rdd = sc.textFile("surnames.txt")
short_surnames_rdd = surnames_rdd.filter(lambda x: len(x) <= 7)
short_surnames = short_surnames_rdd.collect()

print(short_surnames)

first_letter_rdd = short_surnames_rdd.map(lambda x: x[0])
first_letters = first_letter_rdd.collect()

print(first_letters)

numbers_rdd = sc.parallelize(range(1,11))
squares_rdd = numbers_rdd.map(lambda x: x**2)

numbers = numbers_rdd.collect()
squares = squares_rdd.collect()

print(numbers)
print(squares)

union_rdd = numbers_rdd.union(squares_rdd)
print(union_rdd.collect())

intersection_rdd = numbers_rdd.intersection(squares_rdd)
print(intersection_rdd.collect())

subtraction_rdd = numbers_rdd.subtract(squares_rdd)
print(subtraction_rdd.collect())

cartesian_rdd = numbers_rdd.cartesian(squares_rdd)
print(cartesian_rdd.collect())

with open('doc1.TXT', 'r') as file:
  doc1 = file.read()

with open('doc2.txt', 'r') as file:
  doc2 = file.read()


if len(doc1) > len(doc2):
  original_doc = doc1
else:
  original_doc = doc2

print(f"The original document is:\n\n{original_doc}")

longest_surname = surnames_rdd.map(lambda x: len(x)).max()
# longest_surname = surnames_rdd.reduce(lambda x, y: x if len(x) > len(y) else y)

longest_surname

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("Hepatitis Analysis").getOrCreate()

hepatitis_df = spark.read.csv("hepatitis.csv", header=True, inferSchema=True)

avg_age_males = hepatitis_df.filter(hepatitis_df["Sex"] == "male").agg({'Age': 'avg'}).collect()[0][0]

avg_age_males

hepatitis_df.createOrReplaceTempView("hepatitis")

distinct_ages = spark.sql("select distinct Age from hepatitis").collect()

[row['Age'] for row in distinct_ages]

"""# New section"""